name: Build Web

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_appbundle:
    name: Build Flutter (Web)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Java
        uses: actions/setup-java@v1
        with: 
          java-version: "12.x"
          
      - name: Setup Java
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
          
      - name: Pub Get
        run: flutter pub get
        
      - name: Analyze
        run: flutter analyze
        
      - name: Test
        run: flutter test
        
      - name: Clean
        run: flutter clean
    
      - name: Build App Bundle
        run: flutter build web
