name: Flutter Test Analysis Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  flutter_test:
    name: Flutter Test and Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Version
        run: flutter --version

      - name: Doctor
        run: flutter doctor

      - name: Pub Get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Test
        run: flutter test

  build_android:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Build App Bundle
        run: flutter build appbundle

      - name: Build Apk
        run: flutter build apk --release

  build_web:
    name: Build Flutter (Web)
    needs: [flutter_test]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Build web
        run: flutter build web --release

  build_windows:
    name: Build Flutter (Windows)
    needs: [flutter_test]
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Config Windows
        run: flutter config --enable-windows-desktop

      - name: Build Windows
        run: flutter build windows
